### PR TITLE
[Perl] Fix a few regexp related issues and variable with underscore

### PR DESCRIPTION
**Pull request by TheClams**
Fix issue #541 with  space at the beginnign of a regexp
Fix issue #1495 and #1594 where // can break the syntax highlighting
Fix issue #1325 and #1029 related to regexp modifier

Fix issue #1326 with variable starting with underscore

### CODE REVIEW

**Comment by deathaxe** [comment]
Nice, job.

As Perl syntax still "suffers" from Oniguruma I decided to refactor it a week ago, to let it use the latest features and best possible performance.

It works very well right now fixing all the mentioned issues as well and even much more which I found while reading though a couple of available Perl scripts.

Once I am done with the preparations, I look forward for willing testers to find the remaining issues.

**Comment by TheClams** [comment]
Yes it definitely needed a rework, but I could not find the courage to do it ;)

**Comment by wbond** [comment]
@TheClams Have you looked at the work in #1564? If so, I presume it would be safe to close this?

**Comment by wbond** [comment]
Upon further investigation, it was mentioned in #1564 that it covers this, so I am closing. I do appreciate your work, though, @TheClams.

**Pull request closed without merging**
