### PR TITLE
[C] Fix integral constants

### PR DESCRIPTION
**Pull request by jfcherng**
Fix https://github.com/sublimehq/Packages/issues/821.

Ref: https://docs.oracle.com/cd/E19422-01/819-3688/sun.specific.html

### CODE REVIEW

**Comment by wbond** [comment]
Can we get some test assertions for what format these changes are targeting?

**Comment by jfcherng** [comment]
Sure.

**Comment by jfcherng** [comment]
@wbond Sure.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
