### PR TITLE
[Haskell] Unicode Name

### PR DESCRIPTION
**Pull request by AllanZyne**
I try to fix the issues at #214 and #497.
It's not perfect, but better than current one.

### CODE REVIEW

**Comment by wbond** [comment]
Thanks for taking the time to contribute!

Could you add some tests for your changes? This way we can ensure that future changes don't undo work that you did.

From a style standpoint, we use `under_score` variable names instead of `camelCase`. Could you change those over?

**Comment by wbond** [comment]
So it seems these changes remove a bunch of test assertions that were present before. Were those test assertions incorrect in some way?

**Comment by AllanZyne** [comment]
Yes. I test it on Atom, these codes are syntax error!
(Sorry for my poor English!)

qq 20170216100339

**Comment by wbond** [comment]
Just because Atom doesn't syntax highlight them properly, doesn't mean they are invalid.

In general, Atom and Sublime Text have syntaxes and originated from the same source, however Sublime Text has been quite a bit of work in fixing edge-case bugs since we've added a more powerful syntax highlighting engine.

@keith-hall You seem to have contributed these basic tests. Since I know nothing about Haskell, would you mind providing some info about these tests?

**Comment by AllanZyne** [comment]
I'm sorry, then I test on ghci, and yes, you're right.

**Comment by AllanZyne** [comment]
I try to fix it by this way, but I can't pop `meta.function.type-declaration` on comment line.
```yaml
push:
    - meta_scope: meta.function.type-declaration.haskell
    - include: type_signature
    - match: ^(?!\1[ \t]|[ \t]*$)
      pop: true
```
qq 20170216103650

Can I do this?

**Comment by AllanZyne** [comment]
The patch on above is wrong! 
I'm sorry, I can't fix this bug.

**Pull request closed without merging**
