### PR TITLE
[Python] Fix `from . import` relative imports

### LINKED ISSUE #1300: [Python] from . import does not highlight import keyword
The commit 5ad641c4298d828648d36f317db55362a4139a39 somehow broke highlighting of relative imports from current package like:

```python
from . import module
```

The import keyword is scoped as module path instead of keyword.

### PR DESCRIPTION
**Pull request by FichteFoll**
Also highlight invalid names in the `from` section.

Fixes #1300.

### CODE REVIEW

**Comment by deathaxe** [comment]
The primary issue is fixed by this commit 👍 

Question about illegal scoping:

While in

```python
from .module.else import utils
```

the else is scoped as illegal, it is not in the following statement.

```python
from . else import utils
```

I like the idea of catching such common cases and would ask for the second statement to scope `else` (and all the other keywords) as illegal, too.

**Comment by deathaxe** [comment]
Works fine.

**Comment by deathaxe** [comment]
@FichteFoll

Hmm, just found this:

screenshot

Guess there is a `\b` missing somewhere?

**Comment by FichteFoll** [comment]
Nice catch. Fixed.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
