### PR TITLE
[PHP] Add highlight for `@mixin`

### PR DESCRIPTION
**Pull request by husanjun**

### CODE REVIEW

**Comment by jfcherng** [comment]
I suppose `@mixin` is a Laravel-only thing? At least it's non-standard (i.e., it's not listed on https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/index.html#tag-reference). That's why I created phpunit's tags in another category (i.e., https://github.com/sublimehq/Packages/pull/2817/files#diff-c888e442eeecc982b4a2237180bd20fce15694c56d4fa12353b10005ddba5c5eR1560-R1561).

Another question, is `@mixin` the only non-standard tag from Laravel world?

**Comment by husanjun** [comment]
Thank you for your reply
It is for IDE, not specific to Laravel, and is supported by many frameworks and packages,and PHPstorm supports it

Please have a look at
https://github.com/phpDocumentor/fig-standards/issues/35
https://youtrack.jetbrains.com/issue/WI-1730

**Review by jfcherng — APPROVED** [review]

**Comment by jfcherng** [comment]
Thanks for those informations.

**Review by jfcherng — APPROVED** [review]

**Comment by jfcherng** [comment]
Could you either remove or rebase `Add pcntl_async_signals`?

**Comment by husanjun** [comment]
> Could you either remove `Add pcntl_async_signals` to make this PR more clear since it has been merged in another PR? Or merge this branch with upstream's master latest.

Have merged the latest,

**Review by jfcherng — APPROVED** [review]

**Review by deathaxe — APPROVED** [review]

**Pull request merged**
