### PR TITLE
[Lisp] Add support for defparameter|defconstant to function names

### PR DESCRIPTION
**Pull request by mosujiba**

### CODE REVIEW

**Comment by michaelblyons** [comment]
Would you be interested in trying out #2387?

**Comment by mosujiba** [comment]
I'll check it out. Thanks!

**Comment by wbond** [comment]
I'd like to converge the work on Lisp to #2387. Are you okay with closing this and providing feedback or tweaks there @mosujiba?

**Comment by michaelblyons** [comment]
OP has actually done this already. I'm the lazybones who hasn't integrated their PR. 😅

**Comment by mosujiba** [comment]
^

**Pull request closed without merging**
