### PR TITLE
[HTML] add `viewport` meta tag to `html` snippet; fixes #2697

### LINKED ISSUE #2697: [HTML] add viewport meta tag to `html` snippet
- Sublime Version: 3.2.2 Build 3211
- OS Version: macOS 11.1

I appreciate the `html` snippet includes the minimal acceptable HTML file, but I'm glad it has recently [added the `charset` meta tag](https://github.com/sublimehq/Packages/pull/2259) that you need in most, if not all, cases and look forward to having it included in a future release. 

The _other_ thing that you need in most, if not all, cases is opting into mobile optimizations: 

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Based on the 2020 edition of the Web Almanac, a massive yearly survey conducted by HTTP Archive, [42.9%](https://almanac.httparchive.org/en/2020/markup#viewport-specifications) of all web pages they looked at include the proposed version.

This should therefore be an uncontroversial — and, I think, welcome — addition. I can make a PR if needed.

### PR DESCRIPTION
**Pull request by danburzo**
Fixes #2697.

### CODE REVIEW

**Review by keith-hall — APPROVED** [review]

**Comment by deathaxe** [comment]
Fixes #2697

**Comment by danburzo** [comment]
I think it will do that by virtue of the current PR title / commit message, but I'll also update the PR description if that's what you mean.

**Comment by deathaxe** [comment]
It's auto-closed if you can read ...

grafik

**Comment by danburzo** [comment]
Ah, cool tip, I hadn't noticed that piece of UI!

**Review by deathaxe — APPROVED** [review]

**Review by deathaxe — APPROVED** [review]

**Comment by deathaxe** [comment]
Looks like approvals are not accepted from unpriviledged users?

**Review by jfcherng — APPROVED** [review]

**Comment by jfcherng** [comment]
I am going to merge this since it's fairly simple.

**Pull request merged**
