### PR TITLE
Change scope of CSS3 color names

### PR DESCRIPTION
**Pull request by kleinfreund**
Currently, all CSS3 color names are treated as deprecated and thus being highlighted as such in Sublime Text. Since these keywords are widely supported in all browser for a while now ([CSS3 Colors on caniuse.com](http://caniuse.com/#feat=css3-colors)) it’s time to recognize them as regular CSS color names.

- Current scope: `invalid.deprecated.color.w3c-non-standard-color-name.css`
- Proposed change: `support.constant.color.w3c-extended-color-keywords.css`

I just changed the scope and the comment (the referenced link 404’s anyway), because they’re not part of the 2.1 standard.

What do you think? Have I missed something?

### CODE REVIEW

**Comment by wbond** [comment]
Could you add a syntax test file to confirm these changes and (hopefully) prevent regressions in the future? See the Testing section of http://www.sublimetext.com/docs/3/syntax.html for more info.

**Comment by kleinfreund** [comment]
@wbond Sure, added the file. After lecture I’ll test this on my machine. Have to setup a separate Sublime Test with the Packages repository first.

**Comment by kleinfreund** [comment]
I accidentally created the file in the wrong location. I'm on it. Sorry for the mess.

**Comment by kleinfreund** [comment]
I accidentally created the syntax test file in the wrong location. Move it to the CSS directory now. Sorry for the mess.

@wbond Is there a way I can run the syntax tests locally?

**Comment by wbond** [comment]
Yes, while you have the `syntax_test_*` file open, use *Tools > Build*, or cmd/ctrl+b.

**Comment by kleinfreund** [comment]
Got it.

```
Success: 2 assertions in 1 files passed
[Finished]
```

Are those tests sufficient? Let me know if I missed something.

**Comment by wbond** [comment]
Looks good, thanks!

**Pull request merged**
