### PR TITLE
[PHP] Fix comma scope in arrays

### PR DESCRIPTION
**Pull request by jfcherng**
- Fixes https://github.com/sublimehq/Packages/issues/3139
- Add colon scope for https://github.com/sublimehq/Packages/issues/3140

### CODE REVIEW

**Review by Ultra-Instinct-05 — DISMISSED** [review]

**Comment by jrappen** [comment]
@jfcherng so does this fix 3140 as well?

**Comment by jfcherng** [comment]
> @jfcherng so does this fix 3140 as well?

No. It just add a supplement for the `:` scope mentioned in #3140.

**Comment by jfcherng** [comment]
then i think all comma scope should be revised.

**Comment by Ultra-Instinct-05** [comment]
Here is another situation where comma is not scoped.

image

```php
<?php 
    class User {

        public function __construct($username, $email) {
            $this->username = $username;
            $this->email = $email;
        }

    }
    
    $user_1 = new User("John", "a@b.com");
    $user_2 = new User("Doe", "c@d.com");
?>
```

**Comment by jfcherng** [comment]
There are many scattered "comma" scope in the syntax def at this moment. Also, I don't know what scope should be use for the "colon".

**Comment by deathaxe** [comment]
I've choosen `comma` and `colon` in various situations in Java as well as I find them a proper choise in syntaxes which don't make extensive use of semantic highlighting.

Probably `punctuation.separator.sequence` could be used in arrays and `punctuation.separator.arguments` in argument lists, but this would probably require to refine some meta scopes as well to keep consistent. That's probably a future task.

With a look at all currently used scopes there is no real standard to group/categorize 3rd level scopes anyway. Thus a color scheme can address `punctuation.separator` only to create consistent highlighting.

Another question is, whether someone is really interested in highlighting commas different depending on usecase.

So I am fine with the choosen scopes.

**Review by deathaxe — APPROVED** [review]

**Review by deathaxe — APPROVED** [review]

**Review by keith-hall — APPROVED** [review]

**Pull request merged**
