### PR TITLE
[PHP Source] cleaned up one match regexp

### PR DESCRIPTION
**Pull request by aziz**
- No need to be multiline
- Removed the unused named capture

### CODE REVIEW

**Comment by FichteFoll** [comment]
Doesn't need to be quoted either.

**Comment by aziz** [comment]
I think it does because of `{` and `}`.
I was looking at `needs_yaml_quoting` method in `convert_syntax.py`

**Comment by FichteFoll** [comment]
It's fine, I'm working on a new yaml Def and this is perfectly valid because we're in a block context. needs_yaml_quoting is more on the safe side.

**Comment by wbond** [comment]
I've been working on a bunch of fixes to PHP, and this is addressed in those changes.

**Pull request closed without merging**
