### PR TITLE
Update D snippets to match "the D Style"

### PR DESCRIPTION
**Pull request by vladdeSV**
* Updated Dlang snippets to match [the D Style](https://dlang.org/dstyle.html)
 * `{` starts on a new line
* Removed outdated snippets
 * Outdated loggers

### CODE REVIEW

**Comment by FichteFoll** [comment]
Snippets should **always** use tabs as indentation. Tabs are converted to spaces on insertion according to the view settings, but not vice versa.

**Comment by vladdeSV** [comment]
Reverted spaces to tabs

**Comment by wbond** [comment]
Are there modern replacements for the log, out and error snippets removed?

**Comment by vladdeSV** [comment]
Added logging functions per reference http://dlang.org/phobos/std_experimental_logger.html

**Comment by wbond** [comment]
Awesome, thanks for your contribution!

**Comment by vladdeSV** [comment]
:smile:

**Pull request merged**
