### PR TITLE
Recognize Cython file exts as Python

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Strictly speaking, Cython uses a slightly different syntax, but it shouldn't hurt to highlight the files as Python until a proper Cython syntax definition exists (which I currently doubt it will).

**Comment by wbond** [comment]
Alright, let's try it!

**Comment by sweettyler** [comment]
I would prefer having little more (i.e., minimal, not full) support in the default Python syntax definition instead of just adding the file extensions. See in https://github.com/sublimehq/sublime_text/issues/4006 how the keyword "as" is highlighted.

**Comment by Thom1729** [comment]
@sweettyler This is an old PR that's already been merged, and proper Cython support isn't really within its scope. You'll get much more useful feedback if you create a new issue.

**Pull request merged**
