### PR TITLE
[Java] Use same color for constants

### PR DESCRIPTION
**Pull request by lastsecondsave**
See issue #1146.

For default color schemes makes all constants to appear with the same color.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I am strongly opposed to this change since `entity.name.constant` is the more appropriate scope name, yet is receiving a weaker binding.

This should be acceptable if it was the other way around, though.

**Comment by lastsecondsave** [comment]
I see these alternatives:

1. Use same color in color schemes for `constant.other` and `entity.name.constant.other`.
2. Change `entity.name.constant` to `meta.entity.name.constant` and update symbols' list to use this scope. It is not any better than solution implemented but at least this way we don't stack two unrelated scopes together.

**Comment by lastsecondsave** [comment]
To clarify, by 1 I meant to actually update color schemes bundled with Sublime. I too as @Palidino see no reason for uppercase identifiers to have 2 colors, as a Java dev you see all of them as the same thing. Can't say about other languages though.

**Comment by FichteFoll** [comment]
The upper-case variable coloring is based on conventions since there are no hard rules for how constants should be named in any language that I know. For the most part, this does a reasonably good job since many languages have these conventions, and I quite like it. This is currently done in at least Python, Java and Rust.
Again, if people do not want special highlighting, they can easily target the scopes and color them in the usual color, but you can't easily do the opposite.

See also: https://github.com/sublimehq/Packages/pull/1242, https://github.com/sublimehq/Packages/pull/1193

**Comment by lastsecondsave** [comment]
OK, now I agree. Let's deal with color inequality with color schemes. I'll close this PR (previous time I missed the button).

Thank you!

**Pull request closed without merging**
