### PR TITLE
[Python] enable auto match in console input

### PR DESCRIPTION
**Pull request by jrappen**

### CODE REVIEW

**Review by deathaxe — APPROVED** [review]
I'd personally up-vote that with syntax also being enabled.

I may be biased though as I enabled that feature for all widgets in _User/Widget.sublime-settings_.

**Review by jfcherng — APPROVED** [review]

**Comment by keith-hall** [comment]
Does this mean that if we have `auto_match_enabled` set to false in our User preferences file, then this would take precedence? :(

**Comment by jfcherng** [comment]
Then I guess this turns into "the console input widget should respect syntax-specific settings and ST settings"?

**Comment by deathaxe** [comment]
That's the downside, yes. That's one reason why I kept that local so far.

**Comment by deathaxe** [comment]
What I've learned from MarkdownEditing is it's probably easier to add a specific setting locally than to remove it again. I have no strong opinion about what's the better default here.

**Pull request closed without merging**
