### PR TITLE
[CSS] improvements for clip-path polygon

### LINKED ISSUE #1645: css broken?
have no idea if thisis the right place for issue report

im using sublime for python and css, but here is weird something that breaks colouring words

see on picture of screen? word "calc" is has different colour than other calc words. And another problem, "important is also not in color itsblack

is this issue or it should be like this is right now? if issue, how can i fix it?

### PR DESCRIPTION
**Pull request by keith-hall**
fixes #1645

### CODE REVIEW

**Comment by njohnson77** [comment]
this is still not merged? dont see problems with this pr, im still staring down the barrel waiting for the final gates to open, is anyone maintaining this repository

how can i test this changes in my local files so knowing if it works or not, i mean can i use this fix before it is beinging merged into repository master, where is this file in my computer to let me edit my file and test?

**Comment by keith-hall** [comment]
You can [follow the instructions in the readme of this repo](https://github.com/sublimehq/Packages/blob/master/README.md#installation), or install a package like https://packagecontrol.io/packages/PackageResourceViewer and use that to edit files directly.

**Comment by njohnson77** [comment]
> You can follow the instructions in the readme of this repo

Couldn't find it in the readme. The readme is explaining how to clone repo and create simlink, not how to modify .sublime-syntax package file. I see you modified `CSS.sublime-syntax`, where is it located in my sublime installation? I want to edit it using text editor, but it simply doesn't exist anywhere in my computer, i searched all disks and all system folders, such file doesnt exist

>  install a package like 

I dont have internet connection and seems like installing package doesnt work without it.

**Comment by njohnson77** [comment]
> Packages are stored in .sublime-package files, which are zip files with a different extension.

what a dumb decision to rename .zip files to .sublime-package i cant believe. I solved it like this

1. navigate to `C:\Program Files\Sublime Text 3\Packages`
2. Rename `css.sublime-package` to `css.zip`
3. Extract `css.zip`
4. Modify `css.sublime-syntax`
5. Zip it again
6. Rename zip to sublime-package

i think more useful would have had been to allowing users to all names be zip by default, sublimepackage extensions is very not intuitive, zip extensions will had been be better if they implemented in sublime editor

**Comment by njohnson77** [comment]
dont know to use github im leaving bye

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
