### PR TITLE
[Lisp]

### PR DESCRIPTION
**Pull request by gighmmpiob**
Hyphen is a valid character in identifiers:

```lisp
(defun log-1(log-1) (if log-1 "1" "0"))
(format t (log-1 (< 1 2)))
```

### CODE REVIEW

**Comment by michaelblyons** [comment]
I see you have added negative lookbehinds. Can you verify that the change is still compatible with the "fast" regex engine? <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> and choose the regex compatibility option.

**Comment by jfcherng** [comment]
Failing test cases should be added.

**Comment by gighmmpiob** [comment]
Besides hyphens, Lisp allows a lot more other characters inside identifiers. This is a valid code:

```lisp
(write (funcall (lambda (+ -) (* + -)) 3 4)) ; prints 12
```

Here `+` and `-` are bound variables in the lambda function. Only `*` is the actual operator. Any suggestion on how to resolve this? If you want to open a PR yourself let me know and I'll close this.

**Comment by jfcherng** [comment]
> If you want to open a PR yourself let me know and I'll close this.

No. I won't. I don't write Lisp. I can't even know I have solved it or not.

**Comment by michaelblyons** [comment]
I also have never written Lisp, but I spent a little time just now mucking about in the syntax definition cleaning up a little cruft. Some things are not ideal, and some are downright broken: `do*`? wtf?

I have a [still-very-naive modification](https://github.com/michaelblyons/SublimeSyntax-Defaults/tree/lisp/errata) of the existing syntax definition that helps... a little. There are two big problems with a full rewrite: (1) Like @jfcherng, most (all?) of the people who spend time improving the default syntax definitions do not know Lisp, and (2) Edits to the Lisp syntax affect lots of file extensions, so we don't want to accidentally clobber Scheme because we did something for CLisp.

If you're willing to work on a PR, please take what I have (or start from an empty file!). Just be aware that people will review your code. These people may or may not know anything about Lisp, but we'd love to have someone fix it up. See also: #2319 and #1968.

**Comment by jfcherng** [comment]
Reminds me https://iamwilhelm.github.io/bnf-examples/lisp + https://github.com/BenjaminSchaaf/sbnf.

**Pull request closed without merging**
