### PR TITLE
[Scala] Add .sc files to scala

### PR DESCRIPTION
**Pull request by benwaffle**
These are either [scala worksheet](https://github.com/scala-ide/scala-worksheet/wiki/Getting-Started) files or [ammonite script files](https://ammonite.io/#import$file)

### CODE REVIEW

**Comment by benwaffle** [comment]
what else needs to be done to merge this?

**Comment by djspiewak** [comment]
@benwaffle Will has to get to it and merge it. He usually doesn't have a lot of time, so PRs take a while to land on this repo.

**Comment by benwaffle** [comment]
@wbond can you merge this?

**Comment by wbond** [comment]
Thanks @benwaffle, and sorry for the delay!

**Pull request merged**
