### PR TITLE
[Lisp] Expand symbol character support

### PR DESCRIPTION
**Pull request by samuel-jimenez**
Expand characters available to symbols.
Allow Goto Definition on constants and variables as well.

### CODE REVIEW

**Comment by s-clerc** [comment]
Why should globals be in the `entity.`[…]`.functions` scope?

**Comment by samuel-jimenez** [comment]
Good catch; updated.

**Comment by s-clerc** [comment]
Why should globals and constants use the `entity` and `storage` scope at all actually? I just looked at [the docs](https://www.sublimetext.com/docs/3/scope_naming.html#variable) and it seems the appropriate scope would be `variable` but there doesn’t seem to be an appropriate subscope, I’d probably use `variable.other.global` like already done in the file.

For constants `variable.other.const` seems more appropriate.

**Comment by samuel-jimenez** [comment]
In order for Goto Definition to fire.
Currently, this feature will only work with specific scopes. Used in this file are the following:

- entity.name.function
- entity.name.type

There may be others that exist, but documentation is sparse.

Attempting to hack in showInIndexedSymbolList as referenced in [this post](https://forum.sublimetext.com/t/extend-st3-project-tagging/10468/8) allows limited functionality, but only when a symbol is wrapped in parentheses, which is obviously counterproductive for a variable.

**Comment by s-clerc** [comment]
I didn’t realise that; as a temporary solution I guess it’s fine although I worry it’ll mess up syntax highlighting with certain themes such as *Monokai Pro*. Hopefully we can see a better solution for ST4.

**Comment by wbond** [comment]
Is this something that can be converged under #2387? We've got a few different lisp PRs open right now, and it would be great to have the work sort of centralized under the one with the most significant changes. I am sure @michaelblyons would be happy for testing and feedback also.

**Comment by michaelblyons** [comment]
I believe #2387 supersedes this by allowing nearly any character to be used in a symbol. There's a blacklist instead of a whitelist.

**Comment by deathaxe** [comment]
Closing as superseded by #3896.

**Pull request closed without merging**
