### PR TITLE
[Latex] Match sizes using dots as optional argument to newline command

### PR DESCRIPTION
**Pull request by tobiasdiez**
Previously, commands like `\\[1.5ex]` that use a dot in the size were not matched correctly (while `\\[1ex]̀  was recognized). This is fixed.

### CODE REVIEW

**Comment by wbond** [comment]
Sorry for the delay in getting back to you.

Could you add some tests to make sure this is working and doesn't regress?

**Comment by tobiasdiez** [comment]
I've finally found the time to add tests.

**Comment by wbond** [comment]
@randy3k @FichteFoll Either of you have any thoughts on this?

**Comment by randy3k** [comment]
It looks good to me

**Comment by wbond** [comment]
Thanks @tobiasdiez!

**Pull request merged**
