### PR TITLE
[JavaScript] Allow node-specific variables as valid identifiers

### PR DESCRIPTION
**Pull request by Hakerh400**
**Before**

**After**

### CODE REVIEW

**Comment by Thom1729** [comment]
The code change in this PR seems obviously correct. That rule should definitely pop, and it's surely a bug that it wasn't before.

However, I'm confused by the screenshots. After `const`, the syntax should try to match a variable binding pattern, not a variable use. I don't know why it would hit any of the support code unless there's another bug.

I'm on vacation until Monday, so I can't test this at the moment.

**Comment by FichteFoll** [comment]
Support identifiers are matched in assignments.
```yaml
  variable-binding-name:
    - match: (?={{non_reserved_identifier}})
      set:
        - meta_scope: meta.binding.name.js
        - include: literal-variable
```

literal-variable => support =>

There is another pop missing in line 2287:
```yaml
    - match: (?:__defineGetter__|__defineSetter__|__lookupGetter__){{identifier_break}}
      scope: invalid.deprecated.js support.function.js
```

**Comment by Thom1729** [comment]
Weird. I should probably rewrite that part. In the mean time, this PR looks correct, and adding that other missing pop would be even better.

**Comment by wbond** [comment]
Thanks @Hakerh400!

**Pull request merged**
