### PR TITLE
[ShellScript] add missing extensions

### PR DESCRIPTION
**Pull request by jrappen**
see commit for details

### CODE REVIEW

**Comment by jrappen** [comment]
addresses #434

**Comment by FichteFoll** [comment]
I think the long extension (or filename list) for shellscript should be using the `hidden_extensions` setting instead of adding them all to the syntax. See https://github.com/sublimehq/Packages/issues/261.

**Comment by wbond** [comment]
Some of these are just plain wrong, such as [editorconfig](http://editorconfig.org/).

**Comment by wbond** [comment]
I apologize if my comment came off as harsh.

By scanning the list, it seemed like many of these are not shell scripts, but rather various config formats - some of them like INI, others single-line regex patterns.

The Shell Script syntax is in line for an overhaul, and it desperately needs it. However, after the overhaul I don't want to try to be shoehorning various config syntaxes in with bash support. We may even end up splitting bash, zsh and tcsh variants out into their own syntaxes.

**Pull request closed without merging**
