### PR TITLE
[C++] Fix static assert decl

### PR DESCRIPTION
**Pull request by rwols**
This is an attempt to fix https://github.com/sublimehq/Packages/issues/899.

Currently, https://github.com/sublimehq/Packages/issues/899#issuecomment-294446880 still fails, but https://github.com/sublimehq/Packages/issues/899#issuecomment-293856070 is fixed.

### CODE REVIEW

**Comment by rwols** [comment]
beebf3f fixes https://github.com/sublimehq/Packages/issues/899#issuecomment-294446880.

**Comment by wbond** [comment]
It feels odd for `alignof|typeid|static_assert` to push into `data-structures-modifier`. Perhaps we need to clean this up into a new named scope. I can't imagine `friend` is valid inside of any of those.

Additionally, Objective-C++ will need the tests (and possibly changes) ported over.

**Comment by rwols** [comment]
Good point about ObjC++, will have to check if nothing is breaking there.

**Comment by wbond** [comment]
It looks like you missed porting the first test to Objective-C++ and the `keywords-parens` context in Objective-C++ wasn't modified with the changes.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
