### PR TITLE
[PHP] Support PHP 8 attributes syntax change

### PR DESCRIPTION
**Pull request by jfcherng**
Although PHP 8 has been feature-frozen, devs decide to hold a poll for changing the syntax `@@` for `attributes`.

https://wiki.php.net/rfc/shorter_attribute_syntax_change

It looks like to be either (more likely) `#[]` or `@[]`, but it's easy to switch between them in this PR anyway.

---

**UPDATE**: The voting result is `#[]`.

### CODE REVIEW

**Comment by wbond** [comment]
Looks like the voting goes until Sept 2. Currently `#[]` is in first place.

**Comment by jfcherng** [comment]
Yeah, `#[]` is kind of dominating. I don't think the result will change given that there are ~60 PHP core devs will vote and now 56 people has voted.

**Comment by wbond** [comment]
Is this good to merge now?

**Comment by jfcherng** [comment]
> Is this good to merge now?

I think yes since the voting has been ended.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
