### PR TITLE
[WIP] [Docker] add Docker support

### PR DESCRIPTION
**Pull request by jrappen**
This pull request is a **WIP** (work in progress) adding basic Docker support. Feel free to mention me in this thread if you'd like to participate.

---

Goal is merging the best of:

* <https://github.com/asbjornenge/Docker.tmbundle>
  * asbjornenge/Docker.tmbundle#24 /cc @rwols 
  * asbjornenge/Docker.tmbundle#25 /cc @blag
  * /cc @asbjornenge
* basic comment support as shown in the `Git Formats` package
* <https://github.com/moby/moby/tree/master/contrib/syntax/textmate/Docker.tmbundle>
* <https://github.com/jagregory/language-docker>

Tests from:

* <https://github.com/docker-library/docs>
  * <https://docs.docker.com/samples>

---

⚠️ This message will be update when done to have a clear commit message.

### CODE REVIEW

**Comment by jrappen** [comment]
Current status:

screencast

Current issues:

screenshot-issues

**Comment by FichteFoll** [comment]
What's your rationale for this being a default package rather than a third-party package?

**Comment by jrappen** [comment]
I had some free time and took a look at languages that other editors ship by default. I picked a random one missing for Sublime.

I have no strong feelings for this, though. Feel free to close. I'll pick another one.

**Comment by wbond** [comment]
Currently I think we are interested in adding support for:

 - Swift
 - JSX

The JSX route can either be copy-pasted from JavaScript, or will need to have some new features added to the syntax parser to allow extending syntaxes.

Swift is the one that could use the most work, but there are plenty of existing syntaxes that could use a once-over, removing things like backtracking regex expressions adding tests and improving scope names.

I think in general the last thing we need is more syntaxes built into core and requiring Sublime HQ to manage the maintenance of.

**Pull request closed without merging**
