### PR TITLE
[CI] use latest dev build test binary

### PR DESCRIPTION
**Pull request by jrappen**

### CODE REVIEW

**Review by jfcherng — APPROVED** [review]

**Comment by deathaxe** [comment]
FWIW: https://download.sublimetext.com/st_syntax_tests_build_4113_x64.tar.xz is available, too. Not sure if it makes any difference.

**Comment by jrappen** [comment]
> FWIW: [download.sublimetext.com/st_syntax_tests_build_4113_x64.tar.xz](https://download.sublimetext.com/st_syntax_tests_build_4113_x64.tar.xz) is available, too. Not sure if it makes any difference.

Not afaik. This repo has always used Builds from the dev release channel, though.

**Comment by deathaxe** [comment]
I guess, because they are most likely a step ahead.

**Review by deathaxe — APPROVED** [review]

**Comment by deathaxe** [comment]
You are right. I merge it as it probably doesn't make a difference compared to 4113 and is a step ahead anyway.

**Pull request merged**
