### PR TITLE
[C#] Index properties

### PR DESCRIPTION
**Pull request by michaelblyons**
Add class properties to <kbd>cmd</kbd>+<kbd>R</kbd>, and add `(…)` to functions like Python does.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Related: https://github.com/SublimeTextIssues/Core/issues/1676

**Comment by wbond** [comment]
I think we should drop the `(...)` addition for functions and then this should be good to merge. We've got some things in the queue for disambiguating symbols in the symbol list.

**Comment by michaelblyons** [comment]
Since the two files are basically the same now, I merged them. I'm presuming here that the disambig stuff you have in the backend only cares about the scope names, not the files that they are indicated by.

If it does matter, LMK and I'll keep both files.

**Comment by michaelblyons** [comment]
After poking around the new hotness for a bit, I think we want to keep them separate. 😉

**Comment by wbond** [comment]
Thanks for this!

**Pull request merged**
