### PR TITLE
[C++] [Objective-C] Fix too greedy template bracket matchings

### PR DESCRIPTION
**Pull request by rwols**
- Use the generic_lookahead variable to scout ahead for a closing ">" when
  encountering an opening "<" for member variables/methods. [From here](https://github.com/pybind/pybind11/blob/1e6172d4055d654df466f32b8327de7145bc9ea3/include/pybind11/cast.h#L292).
- Inside of a template parameter list, make sure we match "<=" first, before
  we push another template scope. [From here](https://github.com/pybind/pybind11/blob/1e6172d4055d654df466f32b8327de7145bc9ea3/include/pybind11/cast.h#L928).

### CODE REVIEW

**Comment by wbond** [comment]
I had just fixed this for the next dev build, but I like you implementation better since it is more complete. Would you mind resolving the conflict and adding it to Objective-C++ also?

**Comment by rwols** [comment]
I'm stuck at work at the moment but will update this this evening (GMT+1).

**Comment by rwols** [comment]
Should be good now! By the way, that cast.h file is one of the worst files I've come across for highlighting.

**Comment by wbond** [comment]
Thanks for these tweaks!

**Pull request merged**
