### PR TITLE
Add support for Protobuf

### PR DESCRIPTION
**Pull request by gwenzek**
Syntax for Protocol Buffer definition files and Protobuff serialized as text.

Works with proto2 and proto3.
See official Protobuff documentation at https://developers.google.com/protocol-buffers/docs/proto3

There is no official documentation for the text format but it works with the official c++ implementation of the parser.

### CODE REVIEW

**Comment by wbond** [comment]
I imagine based on your previous contributions that this is a solid syntax. However, I don't think Protobuf is something we will want to maintain in the default packages.

Currently I believe we are intending to add just Swift and JSX.

**Comment by jrappen** [comment]
@wbond add a CODEOWNERS file as described in the help pages and assign @gwenzek as being responsible for that subfolder/language? Just an idea.

**Comment by jrappen** [comment]
- https://help.github.com/articles/about-codeowners/
- https://blog.github.com/2017-07-06-introducing-code-owners/

**Comment by jrappen** [comment]
compare #1205

**Comment by Thom1729** [comment]
There is an existing [Protobuf Syntax Highlighting package](https://github.com/VcamX/protobuf-syntax-highlighting). It has not been updated for a few years. The author may be interested in accepting improvements, or even in handing off the package.

**Comment by jrappen** [comment]
@VcamX FYI

**Comment by gwenzek** [comment]
The syntax has been pushed to https://github.com/VcamX/protobuf-syntax-highlighting, and should be available from Package Control.
Thanks.

**Pull request closed without merging**
