### PR TITLE
[PHP] Add lots of "details" fields for AC

### PR DESCRIPTION
**Pull request by jfcherng**
Not all but almost. 

The diff is too large to be shown on GitHub. The whole file is on https://github.com/jfcherng/Sublime-Official-Packages/blob/feat-php-completion-details/PHP/PHP.sublime-completions

---

Data source: https://www.php.net/distributions/manual/php_manual_en.tar.gz
Dealt with scripts: [php-completion-add-details.zip](https://github.com/sublimehq/Packages/files/4741569/php-completion-add-details.zip)

### CODE REVIEW

**Comment by deathaxe** [comment]
Some of the "details" seem very long and feel more like documentations.

**Comment by rwols** [comment]
Good point. I'm guessing this was generated by a python script or something like it. That script should use only the first sentence of the "documentation".

**Comment by jfcherng** [comment]
Completion `details` are now cut and only taken its first sentence with [Natural Language Toolkit](https://www.nltk.org/) (and some manual editing for `i.e.,` and `e.g.,`).

**Comment by jfcherng** [comment]
I just found that the whole PHP's official docs can be downloaded on https://www.php.net/download-docs.php .

I then write some simple script ([php-completion-add-details.zip](https://github.com/sublimehq/Packages/files/4473603/php-completion-add-details.zip)) to deal with it. This PR should be almost perfect right now :smile:

**Comment by jrappen** [comment]
Nice. I found a few of these:

```jsonc
        {
            "trigger": "()",
            "contents": "()"
        },
```

Maybe check the output and remove those?

**Comment by jfcherng** [comment]
> Nice. I found a few of these:
> 
> ```js
>         {
>             "trigger": "()",
>             "contents": "()"
>         },
> ```
> 
> Maybe check the output and remove those?

done

**Comment by jfcherng** [comment]
89 `"details": "Description"` has been removed.

**Pull request merged**
