### PR TITLE
Removes JS and Python snippets

### PR DESCRIPTION
**Pull request by kylebebak**
I code regularly in JS and Python. I can say with confidence that the default JavaScript snippets shipped with ST are useless and/or bizarre. They seem like they were written in 2012, and JS has changed a lot since then.

One of several `for` loop snippets in the `JavaScript` package:

```js
for (var i = 0; i < Things.length; i++) {
  Things[i]
}
```

Why `var` instead of `const` or `let`? Why this style of for loop instead of `for (const <> of <>)`?

-----

The Python snippets are also mostly useless. For example, the `for` loop:

```py
for x in xrange(1,10):
    pass
```

Why `xrange` instead of `range`? Why no space after the comma in `xrange`? Why from 1 to 10? Like, seriously, **what is this???**

-----

Even if they were less useless and/or bizarre, I think forcing the same set of snippets on all ST users is a bad design choice, especially because snippets are difficult to disable, and **impossible to disable in a way that requires no future maintenance**.

Discussion on the broader idea of removing all snippets from language packages here: #1988

### CODE REVIEW

**Comment by michaelblyons** [comment]
I've used both those snippets in the last two weeks. The critical thing is the tabstops, not the defaults (change `xrange(1,10)`  to `range(5)` if you like. I'd support that).

I don't want to start a holy war on which TC39 loop structure someone ought to use, but the one in the snippet has worked since 1995 and still works now. 🤷‍♂

**Comment by kylebebak** [comment]
Rest assured, I'm no holy warrior either. That's why I created this PR... Because even if all the snippets were "great" (which it turns out is very subjective), the main point still stands:

>I think forcing the same set of snippets on all ST users is a bad design choice, especially because snippets are [difficult to disable](https://stackoverflow.com/questions/27995926/how-do-i-disable-snippets-in-sublime-text-3), **and impossible to disable in a way that requires no future maintenance**

Snippets should be defined in user land. There's more discussion in the linked issue.

**Comment by Thom1729** [comment]
It would probably be best to keep the discussion to #1988 to avoid fragmentation. As you say, the quality/relevance of the snippets is very subjective; for any given snippet, some users will likely find it useful and others will find it annoying. So while this PR is specific to Python and JavaScript, it's likely that any discussion of the PR would be applicable to the broader issue.

This is entirely up to you, but it might also be helpful to close this PR for now. That might help to avert the perception of “taking away” features that some users rely on and help to center the discussion instead on how to make snippets work for everyone.

**Comment by kylebebak** [comment]
@Thom1729 
You've convinced me closing it for the time being is a good idea. Looking forward to hearing what you think about it in the #1988

**Pull request closed without merging**
