### PR TITLE
update hook in actually rails 5.x

### PR DESCRIPTION
**Pull request by pandalowry**
before_filter -> before_action, see: https://guides.rubyonrails.org/action_controller_overview.html#filters

### CODE REVIEW

**Comment by wbond** [comment]
Is this only available in 5.x? If so, I'd be hesitant to change since I imagine there are many people using older versions of Rails.

**Comment by pandalowry** [comment]
Yes, 5.x only. I do not know what to do, because I don’t know the proportions of the number of users of old versions. Perhaps you are right and change is not necessary.

**Comment by FichteFoll** [comment]
How old is 5.x? If we can reasonably expect most people to run on the newer version, I think it makes sense to update the snippet. After all, this isn't like we're depreciating or removing syntax highlighting for the old variant.

**Comment by pandalowry** [comment]
Rails [release 5.0 stable](https://github.com/rails/rails/tree/5-0-stable) is same 4 years ago. Now working version is Rails 5.2.3 and moreover, rails 6.0 has been stable for about 5 months. And ultimately, he will be waiting for us. But so far in the documentation of the rails even the master branch builds (6) docs are have snippet who i propose [proof](https://edgeguides.rubyonrails.org/action_controller_overview.html#filters)

**Comment by pandalowry** [comment]
p.s. ling edgeguides.rubyonrails.org is "nightfly" build for official docs.

**Comment by wbond** [comment]
It seems Rails 4 is no longer supported now that 6 is out, so I think it is probably reasonable to update this.

**Pull request merged**
