### PR TITLE
[Java] add tests, improve generic type detection

### LINKED ISSUE #455: Java Storage Syntax Is Broken By Nested Types
In the following image, the second example is the correct variant; but it displays incorrectly due to the `.` character of the `FileManager.FileData` enum.&nbsp; Particularly, the `,` & `>` characters seem to be out of scope.

demo
&nbsp;

-----

&nbsp;
scope1

scope2
&nbsp;

-----

&nbsp;
scope3

scope4
&nbsp;

-----

&nbsp;
__ST Version:__ Stable Channel, Build 3114
__OS:__ Windows 10 Pro (64-bit), Build 10586

### PR DESCRIPTION
**Pull request by keith-hall**
fixes #455

### CODE REVIEW

**Comment by wbond** [comment]
We should ensure that class names are in the symbol list and index. It may also make sense to ensure other data structures are there too (I don't recall too much of what Java entails off of the top of my head).

**Comment by FichteFoll** [comment]
Java's symbol selectors are targetting solely meta scopes for some reason.

**Comment by wbond** [comment]
Yes, a lot of languages target the full class/function definition. This may be useful when scrolling through a list, but isn't so useful for GotoSymbol since it makes fuzzy matching less accurate.

It seems to me the meta scopes could be useful in the future if we implemented some way to create a tree structure for browsing code, however for the symbol indexer it is useless, and for the symbol list I think it is of dubious value.

**Comment by FichteFoll** [comment]
Ah yes, that makes sense.

I can confirm that the indented symbol list is indeed quite useful as an overview (as it is in Python), but not for goto definition. These should probably be separated eventually.

**Comment by wbond** [comment]
Just to clarify, Goto Symbol and Goto Definition are separate and have separate settings in `.tmPreferences` - `showInSymbolList` and `showInIndexedSymbolList`. There are also settings to manipulate the raw content, `symbolTransformation` and `symbolIndexTransformation`.

**Comment by FichteFoll** [comment]
So you're saying that goto definition only looks at the IndexedSymbolList settings, even for the current file? That's very good to know.

Don't forget to add `entity.name.class` (and others?) to `Default/Indexed Symbol List.tmPreferences` then ;)

**Comment by keith-hall** [comment]
I've updated the Java Indexed Symbol List. Enums are scoped the same as classes, so don't need any special rules.

**Comment by FichteFoll** [comment]
In theory, these scopes should be covered by Default/Indexed Symbol List, since that contains `entity.name.function, entity.name.type` currently (and needs to be updated to list the other entities).

**Comment by keith-hall** [comment]
@FichteFoll, but I notice that if I delete the `Packages/Java/Indexed Symbol List.tmPreferences` file, Goto Definition no longer works - it seems to not use the `Packages/Default/Indexed Symbol List.tmPreferences` file?

**Comment by FichteFoll** [comment]
@keith-hall that's because the file doesn't include `entity.name.class` and others like `entity.name.enum` yet and still uses the only recently deprecated `entity.name.type`. Since the Default package is not part of this repo, this has to be bundled in a future build.

**Comment by wbond** [comment]
Just to clarify, `entity.name.type` isn't deprecated for all uses, but `entity.name.class` should be used instead of `entity.name.type.class`.

I have been preferring to enumerate entity name scopes in the tmPreferences files for now so that users with older builds will still get correct functionality.

**Pull request merged**
