### PR TITLE
[CSS] Add support for container at-rule

### PR DESCRIPTION
**Pull request by deathaxe**
This PR adds support for `@container <name> <query> { <rules> }`.

It's fully supported by all current browsers.

see:
- https://developer.mozilla.org/en-US/docs/Web/CSS/@container
- https://drafts.csswg.org/css-contain-3/#container-queries

### CODE REVIEW

**Review by keith-hall — APPROVED** [review]

**Review by michaelblyons — APPROVED** [review]

**Comment by amdd-tim** [comment]
This says 'Approved' but I'm not seeing the syntax highlighting for the container at-rule on Build 4169. Am I missing something?

**Comment by michaelblyons** [comment]
You can follow the steps in the ReadMe to get it now, or you can wait until an official ST release with a changelog message that says "updated syntax highlighting" or something.

**Comment by amdd-tim** [comment]
@michaelblyons thanks. Thought maybe since this was merged before the last Sublime build (4169 24 November 2023), that it might have been included and I was missing something.

**Comment by deathaxe** [comment]
It should have been.

**Comment by amdd-tim** [comment]
@deathaxe okay so I am missing something? The changelog in the app does skip build numbers, but I was assuming having the most recent build would have all the most recent changes, even if I wasn't updating every build.
Screenshot 2024-01-07 at 10 21 56 AM

**Comment by amdd-tim** [comment]
Ah, nevermind. I'm seeing it now. Sorry for the false alarm.

**Pull request merged**
