### PR TITLE
[Rust] fix writeln! macro with one argument, semicolon after where

### LINKED ISSUE #2786: [Rust] code following `where` is not syntax highlighted
- Sublime Version: Version 3.2.2, Build 3211
- OS Version: Arch Linux

```rust
pub trait Foo {
    fn bar()
    where
        Self: Sized;
}

fn main() {
	
}
```

image

### PR DESCRIPTION
**Pull request by keith-hall**
Fixes #2786 as I'm not sure if/when https://github.com/sublimehq/Packages/pull/2305 will ever see any traction.

### CODE REVIEW

**Comment by deathaxe** [comment]
Yeah, first complain about Rust community not willing to cooperate and now contribution pending for ever.

**Comment by keith-hall** [comment]
Not convinced I was complaining, but incremental improvements may be the way to go

**Comment by deathaxe** [comment]
Will complained about Rust community not being very cooperative on discord month ago, which was the reason for #2305 being opened.

**Comment by deathaxe** [comment]
Superseded by #2305

**Pull request closed without merging**
