### PR TITLE
Remove .DS_Store file that made its way into the repo

### PR DESCRIPTION
**Pull request by frou**
It got committed as part of this: https://github.com/sublimehq/Packages/pull/2645

### CODE REVIEW

**Review by Thom1729 — APPROVED** [review]
MY BAD

**Comment by frou** [comment]
Hehe, I only noticed due to having a `launchd` job that runs over my entire filesystem and deletes every `.DS_Store` (except for `~/.DS_Store`). So a deletion ready to be committed showed up in `git status`

**Comment by wbond** [comment]
Thanks!

**Comment by FichteFoll** [comment]
I suggest everyone on mac to add `.DS_Store` to their global gitignore, btw.

**Pull request merged**
