### PR TITLE
[Batch File] Fixing a Comment Highlight Bug

### PR DESCRIPTION
**Pull request by jbw3**
Fixing a bug where @rem was not highlighted as a comment

### CODE REVIEW

**Comment by kleinfreund** [comment]
@jbw3 Please be careful using `@` outside of code formatting on GitHub because it pings users – in this case it pinged the user rem.

**Comment by jfcherng** [comment]
However, `@` is not exclusive to `rem`. The syntax file looks inconsistent using `\b` and `(^|\s)` since previous change. How about let `@` be a symbol, i.e., something like

```yaml
- match: ^\s*@
  scope: whatever
```

**Comment by wbond** [comment]
@jfcherng I believe you are correct that this should be a general symbol, not just for `rem`.

**Comment by jbw3** [comment]
Sounds good. I'll make this change as soon as I get a chance

**Comment by wbond** [comment]
@jbw3 Why the change from `\b` to the lookbehind and lookahead?

In general, moving forward, we are likely to be trying to remove lookbehinds from all of the default syntaxes since it prevents usage of the new regex engine, thus resulting is slower parsing performance.

**Comment by jfcherng** [comment]
@wbond It looks like it's because of my suggestion. lol...

**Comment by wbond** [comment]
@jfcherng Ah, yes! :smile: I guess I missed the end of your comment.

I'll take a look at this in a day or two and see how involved a rewrite of it would be, such as was done with JavaScript.

**Comment by jbw3** [comment]
@wbond I did make the changes per @jfcherng's request :) Should I keep them or go back to `\b`?

**Comment by wbond** [comment]
I believe this issue has been fixed by recent improvements to Batch File

**Pull request closed without merging**
