### PR TITLE
JavaScript with JSX and ES7 decorators

### PR DESCRIPTION
**Pull request by Kronuz**
This adds basic JSX and ES7 decorators to the JavaScript

### CODE REVIEW

**Comment by rwols** [comment]
This will most definitely result in a merge conflict if https://github.com/sublimehq/Packages/pull/1009 gets merged, perhaps branch off of that and see where you land?

**Comment by FichteFoll** [comment]
I'm also not sure whether it was decided to have jsx be a separate syntax or to include it in the Javascript syntax. See the separate issue for details.

**Comment by Thom1729** [comment]
#1009 is merged, and it does look as though the changes conflict. If it helps, I intend to implement decorators as part of #1269 within the next few weeks. (I'm waiting on #1292 to lessen the risk of conflicts, but that's a much smaller change than #1009 was.)

Per #860, the current plan is to add a separate JSX syntax. There are some unanswered questions about the details of maintaining two syntaxes like that. In any case, it would probably be best to finish up #1292 first.

**Comment by michaelblyons** [comment]
Is this obsolete, now that #1483 is merged?

**Comment by Thom1729** [comment]
It is.

**Comment by wbond** [comment]
Decorators are now part of JavaScript, and if we include support for JSX, it will be a separate syntax.

**Pull request closed without merging**
