### PR TITLE
[Python] Properly match all block statements

### PR DESCRIPTION
**Pull request by FichteFoll**
Assign meta and punctuation scopes.

Fixes https://github.com/sublimehq/Packages/issues/703.

### CODE REVIEW

**Comment by wbond** [comment]
Things like this cause issues when embedding the syntax in a markup language. I am going to hold off until I can look into the issue some more.

**Comment by FichteFoll** [comment]
FWIW, the new keywords affected by this are `if` and `while`. `for`, `import` (and `from`) and `except` are already affected by this.

**Comment by FichteFoll** [comment]
Will adding a pop pattern on any unmatched non-whitespace character suffice for getting this merged? Most situations where Python could be embedded are probably markdown and latex, which use `` ` `` and ` \ ` respectively - both invalid in Python (3). Backticks were used in 2 as a `repr()` alias, but I haven't seen them actually being used so far. In fact, they aren't even highlighted currently and probably have never been.

**Comment by FichteFoll** [comment]
I believe with the recent addition of the `embed` feature, this can be looked at again.

**Comment by wbond** [comment]
Let's try it out – thanks for the reminder.

**Pull request merged**
