### PR TITLE
[PHP] Fix php end tags in block comments

### LINKED ISSUE #3535: [PHP] `?>` in multiline comment should not be treated as a closing tag
### What happened?

Reported on https://forum.sublimetext.com/t/code-highlighting-php-in-4142-broken/65903/2

image

The following `?>` is not a closing PHP tag (GitHub handles this correctly).

```php
<?php

/* ?> */
// ^^ - punctuation.section.embedded.end

echo 1;
// <- support.function
```

---

Interestingly, `?>` in single-line comment is a closing PHP tag (ST and GitHub handle this correctly atm).

```php
<?php

// ?>
// ^^ punctuation.section.embedded.end

echo 1;
// <- - support.function
```

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #3535

### CODE REVIEW

**Review by michaelblyons — APPROVED** [review]

**Review by jfcherng — APPROVED** [review]

**Comment by tsymbal** [comment]
Could anybody tell, when we'll be able to use a fix for this issue?

**Comment by jfcherng** [comment]
If you are eager to use it, you can follow readme.
https://github.com/sublimehq/Packages#sublime-packages

**Comment by rogerburkhard** [comment]
Could you consider this fix as critical? Thank you

**Comment by jfcherng** [comment]
> Could you consider this fix as critical? Thank you

I do, but we have no control of making a new (stable) release of ST. @BenjaminSchaaf

**Comment by golgote** [comment]
@michaelblyons  I'm not sure it fixes this issue:

Capture d’écran 2023-01-23 à 08 54 05

**Comment by jfcherng** [comment]
fix what? whats the expexted behavior?

**Comment by golgote** [comment]
Oops, that's the expected behaviour, nevermind

**Comment by danedm** [comment]
Really annoying bug... any way that we can push on to make it critical?

**Comment by jfcherng** [comment]
> Really annoying bug... any way that we can push on to make it critical?

May be enough people to bother `BenjaminSchaaf`.

People can maunally apply the fix but yeah, that won't happen for everyone.

**Comment by jfcherng** [comment]
> How can we manually apply the fix?

https://github.com/sublimehq/Packages/pull/3537#issuecomment-1324948531

**Comment by golgote** [comment]
Can you just release this please, it's getting annoying. Thanks.

**Comment by jfcherng** [comment]
> Can you just release this please, it's getting annoying. Thanks.

Fwiw, you can apply the fix by yourself. Or wait for the notorious long release cycle of stable builds.

**Pull request merged**
