### PR TITLE
[Haskell] match (:@, and :#) in entity.name.function.infix.haskell

### PR DESCRIPTION
**Pull request by moodmosaic**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Same as for #2272.

**Comment by FichteFoll** [comment]
Well, eh, thanks @jrappen, but aside from watching the repository, I already commented on this PR in particular.

**Comment by moodmosaic** [comment]
As per https://github.com/sublimehq/Packages/pull/2272#issuecomment-586863668, closing this since it's merged into https://github.com/sublimehq/Packages/pull/2225. — If https://github.com/sublimehq/Packages/pull/2225 won't get merged into master, I may reopen this.

**Pull request closed without merging**
