### PR TITLE
[JavaScript] Refine ternary conditional sub scope

### PR DESCRIPTION
**Pull request by deathaxe**
Refines `keyword.operator.ternary` to `keyword.operator.conditional.ternary` as some syntaxes may require other types of conditional keywords.

### CODE REVIEW

**Comment by deathaxe** [comment]
Hmm. Who said, running syntax tests by hitting `ctrl+b` in a sublime-syntax files runs tests against all found syntax_test_... files? Seems not to work here.

Test runner says everything is ok, even so it isn't.

grafik

**Review by Thom1729 — APPROVED** [review]

**Comment by Thom1729** [comment]
> Hmm. Who said, running syntax tests by hitting `ctrl+b` in a sublime-syntax files runs tests against all found syntax_test_... files? Seems not to work here.
> 
> Test runner says everything is ok, even so it isn't.
> 
> grafik

That's really weird; it works reliably for me.

**Comment by michaelblyons** [comment]
I do my editing in a different worktree than the one used by Sublime itself. If I run syntax tests on my worktree version, it seems to do something like DeathAxe. Not sure about running them in the symlinked version.

**Comment by Thom1729** [comment]
I have the repo checked out somewhere random, but the JavaScript directory symlinked under Packages, and I edit via the symlinked path.

**Comment by michaelblyons** [comment]
I also have a symlink for ST to load the definitions, but I do not edit there. I edit in a sibling directory to the symlink target and _deploy_ to the symlinked directory.

I have a linter going in my Edit project that compares its files against the currently deployed syndefs. That seems to work fine, since the first-line "This is a test for X" info are ST resources, not file system paths. But if I run the "Run tests" build against the syndef in Edit, it knows how many files are linked against it (or rather against its deployed equivalent?), but it says all their assertions pass.

I don't remember quite why I set this up. It had something to do with integrating long-running branches into my main work environment.

**Comment by deathaxe** [comment]
The main _Packages_ repo is checked out in a data directory. For each syntax I work on, I've created a separate worktree with a sparse-checkout next to the root repository. The worktree folders are symlinked (junction) into ST's packages path, where I do all the editing work.

**Pull request closed without merging**
