### PR TITLE
[Python] Update sql_indicator

### PR DESCRIPTION
**Pull request by deathaxe**
This commit ...

1. copies `sql_indicator` from PHP (PR #3331) to support same kinds of
   sql queries.
   
   `ADD`, `DROP` and `TRUNCATE` are added which are used by some sql
   dialects such as T-SQL.

2. removes `string` scope from queries, keeping only `meta.string`, so
   SQL queries are highlighted the same way as in standalone sql source
   files and to enable code completions, etc. which are normally
   disabled by `string` scope.

### CODE REVIEW

**Review by jfcherng — APPROVED** [review]

**Comment by jfcherng** [comment]
It looks like the removals of `string.quoted.single.python` from meta scope break tests.

**Comment by deathaxe** [comment]
I really hate that splitting of syntax tests as it simply doesn't work to run tests for all at the same time on my box. Hence its too reasy to miss them.

**Review by jfcherng — APPROVED** [review]

**Review by michaelblyons — APPROVED** [review]

**Comment by FichteFoll** [comment]
> I really hate that splitting of syntax tests as it simply doesn't work to run tests for all at the same time on my box. Hence its too reasy to miss them.

Does ST not pick up all relevant test files when you run the "Syntax Test" build on the syntax file?

**Comment by deathaxe** [comment]
Just found the related core issue about that: https://github.com/sublimehq/sublime_text/issues/3771

**Pull request merged**
