### PR TITLE
[C++] [Objective-C] Fix template highlighting

### PR DESCRIPTION
**Pull request by rwols**
Fixes https://github.com/sublimehq/Packages/issues/1032

See: https://stackoverflow.com/questions/10721130/calling-constexpr-in-default-template-argument
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53464
See: https://bugs.llvm.org/show_bug.cgi?id=11851

### CODE REVIEW

**Comment by wbond** [comment]
Are you still planning on adding some more commits (per #1032), or is this good for now?

**Comment by rwols** [comment]
No, I'm not yet done with this.

**Comment by rwols** [comment]
Actually, just merge this as it stands on its own. I'll make a separate issue and PR for the obscure template stuff.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
