### PR TITLE
[Haskell] match (*, @, and #) in keyword.operator.haskell

### PR DESCRIPTION
**Pull request by moodmosaic**

### CODE REVIEW

**Comment by michaelblyons** [comment]
Have you tried out @FichteFoll's rewrite at https://github.com/sublimehq/Packages/pull/2225? Does that address some of the annoyances you're having?

**Comment by moodmosaic** [comment]
Wow! I haven't because I wasn't aware of that :heart: Thank you so much for pointing that out. I'll try it.

**Comment by FichteFoll** [comment]
I definitely added `*` but I don't know about `@#`. Please add comment in that PR and ideally with an example operator, so I can add it.

**Comment by moodmosaic** [comment]
@michaelblyons, I can definitely open those pull requests also to the branch that targets @FichteFoll's rewrite, which I've [just finished reviewing](https://github.com/sublimehq/Packages/pull/2225#pullrequestreview-358614681).

Who's taking the final decision to merge that big pull request, though? If there are no plans having that one merged (the rewrite one), I'm not sure it'll make sense to re-target those pull requests(?)

**Comment by michaelblyons** [comment]
Will Bond is the one who merges PRs to this repo. I can't speak for him, but my observation is  that he typically does big batches of merges at once, often before a significant Dev release. Ideally, you want to have your PR all squared away before that window. Because if you miss it, you'll likely languish until the next one.

With that context, Will has specifically said that reviews of PRs help him out. Bear in mind that the maintainer of a repo like this is often merging syntax definitions for languages _they do not use,_ and are correspondingly timid about doing so if a bad PR might upset lots of grumpy developers. If a large Haskell PR has regular Haskell users who vouch for it, it's more likely to make the cut.

That's part of why FichteFoll asked for volunteers to try out #2225. If the author of a PR is not a normal user of the language, some features may be missed when the PR is created.

The two other benefits you have are:
- FF is likely to accept PRs on a prompter timeline.
    + Will's last cycle was Oct/Nov. The next one might be tomorrow, or it might be June. 🤷‍♂ 
- All the improvements are centralized, so you and others can enjoy them all before they are merged.

**Comment by moodmosaic** [comment]
@michaelblyons, @FichteFoll, I've opened [all pull requests I had](https://github.com/FichteForks/Packages/pulls/moodmosaic) on FF's branch. Hope it helps.

**Comment by moodmosaic** [comment]
I won't be closing those I've opened here, on sublimehq, though. They can be merged if @FichteFoll's pull request never gets merged (which I hope not).

**Comment by FichteFoll** [comment]
I say it's more likely that my PR gets merged because all of your PRs will conflict with it (and one another, even, because you appended all the tests to the bottom) and I will merge your PRs once I reviewed them.

**Comment by moodmosaic** [comment]
>and I will merge your PRs to my fork once I reviewed them, which is going to happen sooner rather than later

@FichteFoll, yes, as soon as any of [those in FichteForks/Packages](https://github.com/FichteForks/Packages/pulls/moodmosaic) gets merged or rejected, I'll update [these in sublimehq/Packages](https://github.com/sublimehq/Packages/pulls?utf8=%E2%9C%93&q=author%3Amoodmosaic+) at the same time.

**Comment by moodmosaic** [comment]
As per https://github.com/sublimehq/Packages/pull/2272#issuecomment-586863668, closing this since it's merged into https://github.com/sublimehq/Packages/pull/2225. — If https://github.com/sublimehq/Packages/pull/2225 won't get merged into master, I may reopen this.

**Pull request closed without merging**
