### PR TITLE
Comment character for Batch Files

### PR DESCRIPTION
**Pull request by dufferzafar**
So you can do `Ctrl + /` to quickly comment/uncomment lines.

### CODE REVIEW

**Comment by jamescostian** [comment]
I just ran into this today and was about to post on the forums about it!

**Comment by dufferzafar** [comment]
I've had this for a long time. But found out about this repo yesterday. :)

**Comment by sublimehq** [comment]
Surely "rem" is much more commonly used for comments than "::"? While both work, I'd think that most users would expect toggle comment to insert a rem.

**Comment by FichteFoll** [comment]
In any case, both should be referenced in the tmpreferences.

**Comment by dufferzafar** [comment]
I can change :: to rem, but I am not sure how I'd add support for both. Any help?

**Comment by FichteFoll** [comment]
Add an additional "TM_COMMENT_START_2" property. http://docs.sublimetext.info/en/latest/reference/comments.html

**Comment by wbond** [comment]
Thanks @dufferzafar for the contribution!

Per your suggestion @FichteFoll, I added `::` as the second version and `rem` is now the default. bf1acacad2d58d1fd378695868726e8c6d5bd1bd

**Pull request merged**
