### PR TITLE
[JavaScript] Added new regexp features

### PR DESCRIPTION
**Pull request by Thom1729**
On top of #1415.

Adds support for:

- Lookbehind assertions.
- Unicode property escapes.
- Named capture groups.
- The dotAll (`s`) flag.

Also adds more detail to some existing constructs and fixes a couple of bugs.

### CODE REVIEW

**Comment by Thom1729** [comment]
Working on the conflict...

**Comment by wbond** [comment]
I was just doing that now since I squashed the previous PR 🙂

**Comment by Thom1729** [comment]
Ah, OK.

**Comment by wbond** [comment]
I ended up rebasing these on top of master and pushing directly there, just for a cleaner history. Thanks!

**Pull request closed without merging**
