### PR TITLE
Adding new C++11 keywords and raw strings

### PR DESCRIPTION
**Pull request by jbw3**
Highlighting the following:
- C++11 keywords
- Raw strings
- Macros \_\_func\_\_, \_\_FUNCTION\_\_, \_\_LINE\_\_, and \_\_FILE\_\_

### CODE REVIEW

**Comment by jfcherng** [comment]
Maybe the plugin [C++11](https://packagecontrol.io/packages/C%2B%2B11) could be take into consideration.

**Comment by txtsd** [comment]
What's the holdup on this PR?

**Comment by wbond** [comment]
@txtsd There are no tests included, which makes reviewing it more complicated. If you wish to contribute, you could write some tests against the current syntax to ensure this doesn't cause regressions. The readme for this repo has more info.

**Comment by txtsd** [comment]
I'll take a look at it!

**Comment by jbw3** [comment]
I've added tests for my changes as well as some regression tests.

**Comment by FichteFoll** [comment]
Shouldn't the string prefixes be scoped as something like storage.type rather than punctuation? I can't compare with how it is in python at this moment, but it is certainly not just punctuation.

**Comment by jbw3** [comment]
I've updated the string prefixes per @FichteFoll's request.

**Comment by wbond** [comment]
Awesome, thanks for taking the time to add the tests and tweak the prefixes to be similar to Python's!

**Comment by wbond** [comment]
I ended up rebasing these on top of master for a cleaner history. Thanks again!

**Pull request closed without merging**
