### PR TITLE
[Markdown] fix problem embedding invalid JavaScript

### LINKED ISSUE #1750: [Markdown] Not closing fenced code block with invalid JavaScript code
image

````
Bug no markdown;

```js
class Research extends React.Component {...})
```

<dd><fieldset>
<fieldset><fieldset>deve-se
</fieldset></fieldset></fieldset></dd>


```

sdf

```


````

### PR DESCRIPTION
**Pull request by keith-hall**
fixes #1750

### CODE REVIEW

**Comment by FichteFoll** [comment]
Why is this necessary, though? Not seeing it right now.

**Comment by keith-hall** [comment]
comment added

**Comment by deathaxe** [comment]
IMHO this is an issue, which should better be fixed in the javascript syntax.

A syntax should never pop off the main as this would mean to raise issues with all syntaxes, which embed it.

**Comment by FichteFoll** [comment]
Superseded by #1782.

**Pull request closed without merging**
