### PR TITLE
[PHP] make "use" consistent with "new" and fix magic methods

### PR DESCRIPTION
**Pull request by keith-hall**
better test coverage for "use" statements in the PHP syntax

### CODE REVIEW

**Comment by keith-hall** [comment]
This also makes the `use` statement consistent with the `new` statement in terms of "classname" coloring:

old:
old_php_use
new:
new_php_use

**Comment by paveljanda** [comment]
👍

**Comment by FichteFoll** [comment]
Please use [Github's reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of "+1"ing posts. Thank you.

**Comment by wbond** [comment]
Thanks!

**Pull request merged**
