### PR TITLE
[meta] Update workflow

### PR DESCRIPTION
**Pull request by jrappen**
- bump dev to 4131

### CODE REVIEW

**Comment by deathaxe** [comment]
Can we address #3257 somehow? Tests on stable fail due to core issue, which was fixed later.

**Comment by jrappen** [comment]
Sure, if you know how.

**Comment by jrappen** [comment]
All I could do, is remove the test on stable (either temporarily or not).

**Comment by jrappen** [comment]
@Thom1729 does this work for you to address the workflow issues in testing #3257?

**Comment by jrappen** [comment]
> @michaelblyons provided the following link:
>
> <https://github.com/actions/toolkit/issues/399#issuecomment-607450398>

---

So it seems this can be fixed by?

1. splitting the workflow into two
2. making SublimeHQ mark one of those checks as required

**Comment by jrappen** [comment]
@sublimehq please:

---

<https://github.com/sublimehq/Packages/settings/branch_protection_rules/new>

For the branch "master" ....

1. Require status checks to pass before merging.
2. Require branches to be up-to-date before merging.
3. We select the status check `ci / Test on dev Build`.

**Comment by jrappen** [comment]
* Not sure if this fixes the problem with the time-out, though.
* The build number was removed from the job name to enable filtering by status check.

**Review by deathaxe — APPROVED** [review]

**Review by jfcherng — APPROVED** [review]

**Pull request merged**
