### PR TITLE
[JavaScript] Scope builtin errors with `builtin`.

### LINKED ISSUE #1980: [JavaScript] Error classes should also have "builtin" scope
Currently, `Error` classes in JavaScript have the `support.class.error.js` scope:

https://github.com/sublimehq/Packages/blob/8c76dd38b2c0049247ec3f57c5b47e07ab52b178/JavaScript/JavaScript.sublime-syntax#L2055-L2056

However, since they are built-in global classes, I feel like they should also have the `support.class.builtin.js` scope, similar to these classes:

https://github.com/sublimehq/Packages/blob/8c76dd38b2c0049247ec3f57c5b47e07ab52b178/JavaScript/JavaScript.sublime-syntax#L2052-L2053

### PR DESCRIPTION
**Pull request by Thom1729**
Fix #1980.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Why not go for `support.class.builtin.error.js`?

**Comment by Thom1729** [comment]
I thought about that, but I'm not sure that the extra `error` scope is really useful. If you think it is, I can certainly add it back.

**Comment by FichteFoll** [comment]
I mean, it wouldn't hurt. I could see use in it for coloring error/exception classes.

It's a consideration for #1842 as well. Which I'll hopefully get to structure into a concrete proposal eventually.

**Comment by Thom1729** [comment]
Apparently this PR is an exact duplicate of #1982.

**Pull request closed without merging**
