### PR TITLE
Add PR and ISSUE templates

### PR DESCRIPTION
**Pull request by buildersbrewery**
see commits for details

### CODE REVIEW

**Comment by buildersbrewery** [comment]
@wbond should I change the wording?

**Comment by FredKSchott** [comment]
:+1: this change will save a lot of time for repo maintainers

**Comment by buildersbrewery** [comment]
Maybe adding:

```markdown
[![Throughput Graph](https://graphs.waffle.io/sublimehq/packages/throughput.svg)](https://waffle.io/sublimehq/packages/metrics/throughput)
```

for this output

[Throughput Graph](https://waffle.io/sublimehq/packages/metrics/throughput)

to the README to show people how the repo is developing would be nice, too.

**Comment by buildersbrewery** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
