### PR TITLE
[CSharp] Add the C# 11 type modifier `file` feature support

### PR DESCRIPTION
**Pull request by lindexi**
See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/file

The `file` is the keyword of type modifier as the type visibility.

### CODE REVIEW

**Comment by michaelblyons** [comment]
Do you want to write some unit tests, too?

**Comment by lindexi** [comment]
Thank you, let me learn how to write unit tests in this project.

**Comment by lindexi** [comment]
@michaelblyons I added the unit test code, could you review my code?

**Comment by michaelblyons** [comment]
I have approved running the tests, but there are some test failures. Once those look good, I think it'll be clear to merge.

**Comment by lindexi** [comment]
@michaelblyons Thank you and I try fix the unit test. Sorry, I'm not familiar with test syntax.

**Comment by michaelblyons** [comment]
If you're having trouble, you can install the PackageDev package, click at end of the line you want tests for in the unit test file, and Cmd+Enter (or Ctrl+Enter) and it should write a test suite for that line.

**Review by michaelblyons — APPROVED** [review]

**Review by deathaxe — APPROVED** [review]

**Pull request merged**
